# Generated by Django 2.1.1 on 2019-01-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='microdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micro1', models.TextField(blank=True, max_length=10000, null=True)),
                ('micro2', models.TextField(blank=True, max_length=10000, null=True)),
                ('micro3', models.TextField(blank=True, max_length=10000, null=True)),
                ('micro4', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
