# Generated by Django 2.1.1 on 2019-01-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('controlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='msg1',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='msg2',
            field=models.TextField(max_length=2000),
        ),
    ]
