# Generated by Django 2.1.1 on 2019-01-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('controlapp', '0002_auto_20190105_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='msg3',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='msg4',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='msg1',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='msg2',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
