# Generated by Django 2.1.1 on 2019-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_computer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('heading1', models.CharField(blank=True, max_length=50, null=True)),
                ('para1', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading2', models.CharField(blank=True, max_length=50, null=True)),
                ('para2', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading3', models.CharField(blank=True, max_length=50, null=True)),
                ('para3', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading4', models.CharField(blank=True, max_length=50, null=True)),
                ('para4', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading5', models.CharField(blank=True, max_length=50, null=True)),
                ('para5', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading6', models.CharField(blank=True, max_length=50, null=True)),
                ('para6', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading7', models.CharField(blank=True, max_length=50, null=True)),
                ('para7', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading8', models.CharField(blank=True, max_length=50, null=True)),
                ('para8', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading9', models.CharField(blank=True, max_length=50, null=True)),
                ('para9', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading10', models.CharField(blank=True, max_length=50, null=True)),
                ('para10', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading11', models.CharField(blank=True, max_length=50, null=True)),
                ('para11', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading12', models.CharField(blank=True, max_length=50, null=True)),
                ('para12', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading13', models.CharField(blank=True, max_length=50, null=True)),
                ('para13', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading14', models.CharField(blank=True, max_length=50, null=True)),
                ('para14', models.TextField(blank=True, max_length=1000, null=True)),
                ('heading15', models.CharField(blank=True, max_length=50, null=True)),
                ('para15', models.TextField(blank=True, max_length=1000, null=True)),
                ('footer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
